card_data_query = "Select * from google_ads.fn_dashboard_metrics_{filter}('{org_id}', '{channel}', '{start_date}', '{end_date}')"
chart_data_query = "Select * from google_ads.fn_dashboard_metrics_trends_{filter}('{org_id}', '{channel}', '{start_date}', '{end_date}')"
table_1_data_query = "select * from google_ads.fn_dashboard_metrics_gender('{org_id}','{channel}','{start_date}','{end_date}');"
table_2_data_query = "select * from google_ads.fn_dashboard_metrics_devices('{org_id}','{channel}','{start_date}','{end_date}');"
word_cloud_1_data_query = "select * from google_ads.fn_dashboard_metrics_keywords('{org_id}','{channel}','{start_date}','{end_date}');"
word_cloud_2_data_query = "select * from google_ads.fn_dashboard_metrics_bid_strategy('{org_id}', '{channel}','{start_date}','{end_date}');"
distinct_organization_query = "select * from public.organization_organization;"
distinct_product_query = "select * from public.organization_product;"
subscription_query = "select * from public.subscription_subscription where organization_id = '{organization_id}';"
